function A_est = arnoldi_convergence(A,K)
% ARNOLDI_CONVERGENCE - This function examines the convergence behavior of 
% Arnoldi iteration for approximating a matrix A in Krylov subspaces.
% Specifically, the function employs Arnoldi iteration to approximate matrix A,
% computes the relative error between the eigenvalues of the approximated matrix
% and those of the original matrix A, and plots this error as a function of the 
% dimension of the Krylov space.
%
% Parameters:
% - A: Input square matrix to be approximated (nxn)
% - K: Number of Arnoldi iterations (dimension of Krylov space)
%
% Outputs:
% - A_est: Approximated matrix of A at each iteration k, represented in Krylov
%          subspace generated by Arnoldi iteration.
%
% Dependencies:
% - arnoldi_iteration: A function that implements one step of Arnoldi iteration
%
% Usage:
% >> A_est = arnoldi_convergence(A, K)
%
% Notes:
% - Function assumes A to be square; error-checking is not implemented.
%
% Author: Nathan Rousselot

    err = zeros(K,1);
    n = length(A);
    u = randn(n,1);
    u = u/norm(u,2);
    for k = 1:K
        [V,H] = arnoldi_iteration(A,u,k);
        A_est = V*H*V';
        err(k) = norm(eigs(A_est)-eigs(A),2)/norm(eigs(A),2);
        disp(k)
    end
    figure(1)
    semilogy(err,'k','LineWidth',0.9)
    xlabel('Dimension of the Krylov space')
    ylabel('Relative Error')
    grid on
end